---

- name: Do not autoconfigure OpenLDAP
  debconf:
    name: "slapd"
    question: 'slapd/no_configuration'
    value: true
    vtype: "boolean"

- name: Install OpenLDAP packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: [ 'slapd', 'ldap-utils', 'python-ldap' ]

- name: Delete the configuration directory
  file:
    path: "/etc/ldap/slapd.d"
    state: absent

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
