---

- name: Check if BaseDN administrator password hash exists
  stat:
    path: '{{ slapd__basedn_admin_hash }}'
  register: slapd__register_local_basedn_admin_hash
  become: False
  delegate_to: 'localhost'
  no_log: True

- name: Read hash of BaseDN administrator password
  set_fact:
    slapd__register_basedn_admin_hash: '{{ lookup( "file", slapd__basedn_admin_hash) }}'
  when: slapd__register_local_basedn_admin_hash.stat.exists
  no_log: True

- name: Generate BaseDN administrator password
  shell: slappasswd -s {{ lookup('password', slapd__basedn_admin_password + ' length=' + slapd__password_length) }}
  register: slapd__register_basedn_admin_password
  when: (slapd__register_basedn_admin_hash is undefined or
         (slapd__register_basedn_admin_hash is defined and not slapd__register_basedn_admin_hash))
  changed_when: False
  no_log: True
  always_run: yes

- name: Save hash of BaseDN administrator password
  copy:
    content: '{{ slapd__register_basedn_admin_password.stdout }}'
    dest: '{{ slapd__basedn_admin_hash }}'
  become: False
  delegate_to: 'localhost'
  when: (slapd__register_basedn_admin_hash is undefined or
         (slapd__register_basedn_admin_hash is defined and not slapd__register_basedn_admin_hash))
#  no_log: True

